name: bodai
description: Meal prediction and automated planning.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+44

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  supabase_flutter: ^0.2.12
  freezed_annotation: ^1.1.0
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  json_annotation: ^4.4.0
  image: ^3.1.3
  image_picker: ^0.8.4+11
  flutter_typeahead: ^3.2.4
  flutter_keyboard_visibility: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true

  assets:
     - assets/images/
