name: bodai
description: Meal prediction and automated planning.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+39

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.13
  supabase_flutter: ^0.2.12
  flutter_riverpod: ^1.0.3
  flutter_typeahead: ^3.2.4
  json_annotation: ^4.4.0
  package_info: ^2.0.2
  image_picker: ^0.8.4+8
  image: ^3.1.0
  in_app_purchase: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.5
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
     - assets/images/
