// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERmRI_WL8sin5ngj0meV4eZyx4XsM-do',
    appId: '1:740317313333:web:2ca88a7c0c22aba7f7747c',
    messagingSenderId: '740317313333',
    projectId: 'bodai-29090',
    authDomain: 'bodai-29090.firebaseapp.com',
    storageBucket: 'bodai-29090.appspot.com',
    measurementId: 'G-2TBMFDTMCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_UjVwIJPRe-bvQkFv9QSTjA6EHivui4',
    appId: '1:740317313333:android:7701ca89436dfa7af7747c',
    messagingSenderId: '740317313333',
    projectId: 'bodai-29090',
    storageBucket: 'bodai-29090.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtPhjhGMtn83yPcrVN98DrIB2QKVMsgZY',
    appId: '1:740317313333:ios:2de9bed050cda8f9f7747c',
    messagingSenderId: '740317313333',
    projectId: 'bodai-29090',
    storageBucket: 'bodai-29090.appspot.com',
    iosClientId: '740317313333-cspqhecki7rk9nuq6u0mos4frs4jcqsk.apps.googleusercontent.com',
    iosBundleId: 'co.bodai.bodaiapp',
  );
}
